spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
#  profiles:
#    active: prod
  config: # from here this is for cloud config where fetching the configuration from the GIT
    import: optional:configserver:http://localhost:8086
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql : true
server:
  port: 8081
  servlet:
    context-path: /userService



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

service:
  api:
    rating-url: http://RATING-SERVICE/ratingService/rating/hotelId/
    hotel-url: http://HOTEL-SERVICE/hotelService/hotels/findByHotelId/

#actuator configuration and circuitbreaker
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

# resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker: # this name should be matched from the UserController class which is written inside the @CircuitBreaker
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED