spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql : true
server:
  port: 8081
  servlet:
    context-path: /userService

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:0786/eureka

service:
  api:
    rating-url: http://RATING-SERVICE/ratingService/rating/hotelId/
    hotel-url: http://HOTEL-SERVICE/hotelService/hotels/findByHotelId/