spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    application:
      name: refund-service
server:
  port: 8081
  servlet:
    context-path: /userService